version: '3'
services:
  nginx-portal:
      image: 'nginx:1.17-alpine'
      container_name: 'nginx-portal'
      ports:
        - "80:80"
        - "443:443"
      volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      environment:
        - NGINX_PORT=80
      extra_hosts:
        - "portal.graphql.com:192.168.1.11"
        - "api.graphql.com:192.168.1.11"
  soc-portal:
      image: 'soc-portal:1.0.0'
      container_name: 'soc-portal'
      ports:
        - 80:80
      depends_on:
         - nginx-portal
