version: '3'
services:
  database:
    image: 'mongo:4.0'
    container_name: 'mongo'
    environment:
      MONGO_INITDB_DATABASE: soc
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
    - '27017-27019:27017-27019'
    volumes:
    - ./data/db:/data/db
    - ./data/configdb:/data/configdb

  mongo-express:
    image: mongo-express
    container_name: 'mongo-express'
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
    depends_on:
      - database